baseurl: 'https://temama.soy'
title: temama.soy
paginate: 5
theme: "PaperMod"
copyright: © 2024 Toshihito Kon CC BY-SA
timezone: Asia/Tokyo

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

# Langage Settings
languageCode: ja
DefaultContentLanguage: ja
hasCJKLanguage: true
languages:
  ja:
    languageName: Japanese
    Title: temama.soy
    weight: 1
    Params:
      homeInfoParams:
        title: temama.soy - temama's blog 
      dateFormat: 2006-01-02
  en:
    languageName: English
    Title: temama.soy
    weight: 2
    Params:
      homeInfoParams:
        title: temama.soy - temama's blog 

# ref: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/
params:
  mainSections:
    - blogs
    - tools

  env: production
  title: temama.soy
  # description: "temama.soy"
  keywords: [Blog, Portfolio]
  author: "Toshihito Kon"
  images: ["/assets/img/icon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShareButtons:
    - x
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
    enabled: false

  socialIcons:
    - name: GitHub
      url: "https://github.com/ToshihitoKon"
    - name: Bluesky
      url: "https://bsky.app/profile/temama.bsky.social"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 20
    - identifier: tools
      name: Tools
      url: /tools/
      weight: 30
