receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: "http://metrics-storage:9009/api/v1/push"
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

extensions:

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
